### ISSUE TITLE
Adicionar suporte a embeds em YAML

### ISSUE THREAD

**Issue by MrPowerGamerBR** [LorittaBot/Loritta#40]
Em espera até #39 ser implementado.

```yml
content: "{@user}"
embed:
  color: -9270822
  title: "👋 Bem-vindo(a)!"
  description: Olá {@user}, espero que você se divirta no meu servidor! <:loritta:331179879582269451>
  author:
    name: "{user}#{user-discriminator}"
    icon_url: "{user-avatar-url}"
  thumbnail:
    url: "{user-avatar-url}"
  footer:
    text: 'ID do usuário: {user-id}'
```
